<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Perscom</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>False</UseWPF>
    <Platforms>x64</Platforms>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>perscom_icon_sv6_icon.ico</ApplicationIcon>
    <StartupObject>Perscom.Program</StartupObject>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Controls\ShadowLabel.cs">
      <SubType>Component</SubType>
    </Compile>
    <EmbeddedResource Include="Resources\FluentPerscomBlue.tssp" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="perscom_icon_sv6_icon.ico" />
    <Content Include="ToDo.txt" />
    <Content Include="Config\Names.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CrossLite\CrossLite\CrossLite.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Images\flags\" />
    <Folder Include="Images\soldiers\" />
    <Folder Include="Images\ranks\US SpaceForce\" />
    <Folder Include="Images\ranks\US Navy\" />
    <Folder Include="Images\ranks\US AirForce\" />
    <Folder Include="Images\ranks\US Marines\" />
    <Folder Include="Images\ranks\US Army\" />
    <Folder Include="UI\SimResult\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="Google.GenAI" Version="1.6.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="NodaTime" Version="3.3.2" />
    <PackageReference Include="UI.for.WinForms.AllControls.Net80">
      <Version>2026.1.415</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Database\Entities\BilletCustomGenerator.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Application\Condition.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Application\Epoch.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Application\ExceptionHandler.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Application\FormStyling.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Application\ImageAccessor.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Application\Program.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Application\Range.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Application\SyncProgress.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Application\TaskProgressUpdate.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Controls\CustomPanel.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Controls\GradientPanel.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Controls\ListViewWithReordering.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Controls\MyCheckBox.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Controls\MyCheckBox.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Controls\ShadowLabel.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\AppDatabase.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\BaseDatabase.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Abstract\AbstractBilletStatistics.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Abstract\AbstractFilter.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Abstract\AbstractSort.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Abstract\BilletCustomProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Assignment.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\BilletOrderedProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\BilletRandomizedProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\OrderedPool.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\OrderedPoolCareer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\OrderedPoolFilter.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\OrderedPoolGroup.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\OrderedPoolSorting.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\OrderedPoolSpecialty.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\OrderedProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\OrderedProcedureCareer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\RandomizedPool.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\RandomizedPoolCareer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\RandomizedPoolFilter .cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\RandomizedPoolSorting.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\RandomizedProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet Procedures\RandomizedProcedureCareer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Billet.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletCareer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletCatagory.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletCustomGenerator.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletExperience.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletSelectionFilter.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletSelectionGroup.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletSelectionSorting.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletSpecialty.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletSpecialtyRequirement.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\BilletStatistics.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\CareerGenerator.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\CareerLengthRange.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\DbVersion.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Echelon.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Experience.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\IterationDate.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\PastAssignment.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Position.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\PositionStatistics.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Promotion.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Rank.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\RankGradeStatistics.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Soldier.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\SoldierExperience.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\SoldierUnitAttachment.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Specialty.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\SpecialtyAssignment.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\SpecialtyGradeStatistics.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\Unit.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\UnitAttachment.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\UnitTemplate.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Entities\UnitTemplateAttachment.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\Enums.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\MigrationWizard.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\RankCache.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Database\SimDatabase.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Extensions\ChartColorPallets.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Extensions\DateTimeExt.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Extensions\DictionaryExtensions.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Extensions\IEnumerableExtensions.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Extensions\IntExtensions.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Extensions\ListExtensions.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Extensions\NumericUpDownExtensions.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Extensions\ProgressBarExtensions.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Extensions\StopWatchExtensions.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\obj\Release\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\obj\Release\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\obj\Release\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Properties\AssemblyInfo.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Properties\Resources.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Properties\Settings.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\BilletWrapper.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\CryptoRandom.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Enums.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Events\LateralPositionExchangeEventArgs.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Events\PositionAndRankChangeEventArgs.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Events\PositionChangeEventArgs.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Events\RankChangeEventArgs.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Events\SpecialtyChangeEventArgs.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\ISpawnable.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\OrderedProcedureWrapper.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\PositionWrapper.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Procedures\AbstractSelectionProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Procedures\LateralOnlyProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Procedures\OrderedSelectionProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Procedures\PromotionOnlyProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Procedures\PromotionOrLateralProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Procedures\RandomizedSelectionProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Procedures\SoldierEntryProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\PromotableStatus.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\RandomizedProcedureWrapper.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\RandomNameGenerator.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\RankType.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\SelectionProcedure.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\SimulationCache.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\Simulator.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\SimulatorSettings.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\SoldierFormWrapper.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\SoldierPoolWrapper.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\SoldierWrapper.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\SpawnGenerator.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\UnitBuilder.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\UnitStatistics.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\UnitTemplateWrapper.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Simulation\UnitWrapper.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\BilletEditorForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\BilletEditorForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\CareerGeneratorEditorForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\CareerGeneratorEditorForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\CareerLengthEditorForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\CareerLengthEditorForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExceptionForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExceptionForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExperienceForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExperienceForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExperienceNameChangeForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExperienceNameChangeForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExperienceSelectForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExperienceSelectForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\MainForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\MainForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\OrderedPoolForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\OrderedPoolForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\OrderedProcedureForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\OrderedProcedureForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\PositionHistoryForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\PositionHistoryForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\PositionStatsForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\PositionStatsForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RandomizedPoolForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RandomizedPoolForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RandomizedProcedureForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RandomizedProcedureForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RankEditorForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RankEditorForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RequiredSpecialtiesForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RequiredSpecialtiesForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SimResultViewForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SimResultViewForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierEditForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierEditForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierFilterForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierFilterForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierSortingForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierSortingForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierViewForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierViewForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SpecialtyEditorForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SpecialtyEditorForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\TaskForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\TaskForm.Designer.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\UnitTypeManagerForm.cs" />
    <Compile Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\UnitTypeManagerForm.Designer.cs" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\Properties\Resources.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\BilletEditorForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\CareerGeneratorEditorForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\CareerLengthEditorForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExceptionForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExperienceForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExperienceNameChangeForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\ExperienceSelectForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\MainForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\OrderedPoolForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\OrderedProcedureForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\PositionHistoryForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\PositionStatsForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RandomizedPoolForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RandomizedProcedureForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RankEditorForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\RequiredSpecialtiesForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SimResultViewForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierEditForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierFilterForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierSortingForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SoldierViewForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\SpecialtyEditorForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\TaskForm.resx" />
    <EmbeddedResource Remove="PerscomSimulator_Backup_2019.05.19_11.47.16\UI\UnitTypeManagerForm.resx" />
    <EmbeddedResource Remove="UI\ExceptionForm.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\FluentPerscomBlue.tssp" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Images\ranks\US Army\E2.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E3.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E4.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E4_spec.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E5.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E6.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E7.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E8_1sg.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E8_msg.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E9_csm.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E9_smg.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Army\E9_smoa.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E2.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E3.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E4.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E5.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E6.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E7.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E8_1sg.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E8_msgt.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E9_msgysgt.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E9_sgm.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Marines\E9_sgmotmc.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\1LT.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\2LT.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\BG.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\COL.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\CPT.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\GEN.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\LTC.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\LTG.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\MAJ.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Images\ranks\US Officer\MG.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>